name: flashcardstudyapplication
description: A medical flashcard application for students

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.8.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  timeago: ^3.6.0
  cached_network_image: ^3.3.0
  flutter_application_1: ^0.0.2
  http: ^1.2.2
  uuid: ^4.2.1
  yaml: ^3.1.2 
  flutter_riverpod: ^2.6.1  # Use this instead of just riverpod
  riverpod_annotation: ^2.3.3 # Optional but recommended
  app_links: ^6.3.2
  path_provider: ^2.0.9
  google_fonts: ^6.2.1
  purchases_flutter: ^4.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/medical_bg.jpg
    - lib\core\config\api.config.yaml
    - 'assets/images/logo.png'
    
  # Add custom fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf