name: flashcardstudyapplication
description: A flashcard Study application for students

publish_to: 'none'

version: 2.0.0+3

environment:
  sdk: '>=3.0.0 <25.0.0'

flutter_icons:
  image_path: "assets/icons/logo.jpg" 
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true

dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.8.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  timeago: ^3.6.0
  cached_network_image: ^3.3.1
  flutter_application_1: ^0.0.2
  http: ^1.2.2
  uuid: ^4.2.1
  yaml: ^3.1.2 
  flutter_riverpod: ^2.6.1  # Use this instead of just riverpod
  riverpod_annotation: ^2.3.3 # Optional but recommended
  app_links: ^6.3.2
  path_provider: ^2.0.9
  google_fonts: ^6.2.1
  dart_jsonwebtoken: ^2.14.2
  sign_in_with_apple: ^6.1.3
  google_sign_in: ^6.2.2
  purchases_flutter: ^8.4.4
  purchases_ui_flutter: ^8.4.4
  url_launcher: ^6.0.0
  google_sign_in_android: ^6.1.33
  posthog_flutter: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  archive: ^3.4.10
  path: ^1.8.3
  flutter_cache_manager: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/logo.jpg
    - assets/images/medical_bg.jpg
    - lib/core/config/api.config.yaml
    - 'assets/images/logo.png'
    - 'assets/logos/light mode/logo-lightmode.png'
    - 'assets/logos/dark mode/logo-darkmode.png'
    
  # Add custom fonts if needed
  fonts:
    - family: BankGothic
      fonts:
        - asset: assets/fonts/BankGothic-Bold.ttf
          weight: 700